### ISSUE TITLE
Drawing is jumping when starting a new Line or when saving the Image

### ISSUE THREAD

**Issue by karatektus** [nhnent/tui.image-editor#151] opened 2019-02-15 14:47 UTC
## Version
3.5.0

## Development Environment
Windows

## Current Behavior
When starting a second line (or saving the image) the last one jumps to the upper left

## Expected Behavior
Drawings should stay where they are

Its basically the same issue as in #96 but I am not implementing my own UI but using the built in one

**Comment by jinwoo-kim-nhn** [comment] 2019-02-21 09:52
@karatektus hello
The problem may appear if the canvas area is damaged.

However, the information you provide is so poor that it is difficult to give clear help.

You will not have any problems if you use the includeUi option by setting the initial image as shown below, or using the load button at the top.


```js
   ...
   options.includeUI: {
       loadImage: {
           path: 'img/sampleImage2.png',
           name: 'SampleImage'
       },
       ...
   };
   ...

```


Perhaps you have changed the image through the API of the imageEditor instance other than the one provided by ui.

if so, api of below  may be helpful. Good luck.

[imageEditorInstance.ui.resizeEditor()](http://nhnent.github.io/tui.image-editor/latest/Ui.html#resizeEditor)

**Comment by pritamgudekar** [comment] 2019-03-09 22:24
I am also getting same issue for drawing free line where as its working fine for straight line and all other features. Following is the code that I am trying as per the suggestions:

if (!this.imageEditor) {
      this.imageEditor = new ImageEditor(document.querySelector('#tui-image-editor'),
      {
        includeUI: {
          loadImage: {
            path: this.editImage.fileUrl,
            name: this.editImage.fileName
          },
          theme: this.imageTheme.blackTheme,
          menu: ['shape', 'text', 'draw', 'rotate', 'flip', 'crop'],
          initMenu: 'draw',
          menuBarPosition: 'bottom'
        },
        cssMaxWidth: 700,
        cssMaxHeight: 500,
        selectionStyle: {
          cornerSize: 20,
          rotatingPointOffset: 70
        }
      });
    }
    this.imageEditor.loadImageFromURL( this.editImage.fileUrl, this.editImage.fileName).then(result => {
      // --- check result
      this.imageEditor['ui'].resizeEditor();
     // --- Using this.imageEditor.ui.resizeEditor() gives "Property 'ui' does not exist on type 'ImageEditor'." that's why used as above.
    });

Any input on what things need to be done further to fix this issue?

**Comment by junghwan-park** [comment] 2019-03-15 01:14
@karatektus 
I found bug what your said. Thanks.

@pritamgudekar 
Are you using typescript? `ui` property type definition is missing. I'll add all instance's property type definitions. Thanks!

**Comment by pritamgudekar** [comment] 2019-03-15 23:21
> @karatektus
> I found bug what your said. Thanks.
> 
> @pritamgudekar
> Are you using typescript? `ui` property type definition is missing. I'll add all instance's property type definitions. Thanks!

Yes. Using typescript. The above code is in typescript page where tui library is using.
Also I checked the tui-image-editor.js library but where to refresh the editor for free line drawing?

**Comment by junghwan-park** [comment] 2019-03-18 11:28
@pritamgudekar 
No. This bug is nothing to do with `this.imageEditor.ui.resizeEditor()`. Type missing issue is different issue.
I'll resolve free drawing line jumping issue at #167. So, closing this issue.

**Comment by pritamgudekar** [comment] 2019-03-18 17:53
Thank you @junghwan-park. It would be great when you will notify on its fix.
Thanks.

**Closed** 2019-03-21 12:36 UTC
Labels: question

**Comment by pritamgudekar** [comment] 2019-06-25 18:20
> @pritamgudekar
> No. This bug is nothing to do with `this.imageEditor.ui.resizeEditor()`. Type missing issue is different issue.
> I'll resolve free drawing line jumping issue at #167. So, closing this issue.

Hi @junghwan-park 
Any fixes for this issue? If yes then from where we will get the reference of this fix?

**Comment by hemulslava** [comment] 2019-07-01 12:37
Hey @junghwan-park!
This is a significant problem for me too. Will you fix it?

**Comment by dimakovalevskyi** [comment] 2019-07-09 14:38
Try to use fabric.js 1.6.7. It helps me.

**Comment by pritamgudekar** [comment] 2019-09-24 00:01
Thanks @dimakovalevskyi for the suggestion, the only thing is here I could find only drawing shapes only, along with that I need some more feature that tui image library is having.

Thanks again.

**Comment by pritamgudekar** [comment] 2019-09-24 00:01
Hi @junghwan-park
Any update on this issue?

**Comment by pritamgudekar** [comment] 2020-04-15 01:24
@dimakovalevskyi - I checked and I am already using fabric.js 1.6.7. but the issue is still reproducing.

Hi @junghwan-park - Is the free line jumping issue resolved? If yes could you please provide the version, if any, for the fixed changes.

Appreciates your help towards the same.

Thanks,
Pritam
